server:
  port: 9000

spring:
  application:
    name: zuul-gateway 

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.0.178:8761/eureka/