server:
  port: 8761

eureka:
  instance:    
    prefer-ip-address: true  
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.0.178:8761/eureka/

spring:
  application:
    name: eureka-server