server:
  port: 8088

spring:
  application:
    name: config-server
  profiles: 
    active: native
  cloud:
    config:
      server:
        native:
            search-locations: classpath:/config

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.0.178:8761/eureka/